<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Try...Catch</title>
    <link rel="stylesheet" href="../css/style.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Merriweather+Sans&family=Montserrat&family=Sacramento&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="middle-container">
        <div class="profile">
            <img class="profile-image" src="../images/try.jpg" alt="man-avatar">
            <h2>Try...Catch</h2>
        </div>
        <div class="topics">
            <h3 class="topic-description">The try keyword creates a try...catch statement. The try statement allows you
                to define a block of
                code to be tested for errors while it is being
                executed.</h3>
            <h3 class="topic-description">The catch keyword catches exceptions generated by try statements. The catch
                statement allows you to
                define a block of code to be executed, if an error occurs in the try block. </h3>
            <h3>Syntax</h3>
            <div class="syntax">
                <p class="code">try {</p>
                <p class="code">// Block of code to try</p>
                <p class="code">}</p>
                <p class="code">catch(Exception e) {</p>
                <p class="code">// Block of code to handle errors</p>
                <p class="code">}</p>
            </div>
            <h3>Consider the following example</h3>
            <div class="syntax">

                <p class="code">public class Main {</p>
                <p class="code">&emsp;public static void main(String[ ] args) {</p>
                <p class="code">&emsp;&emsp;int[] myNumbers = {1, 2, 3};</p>
                <p class="code">&emsp;&emsp;System.out.println(myNumbers[10]); // error!
                </p>
                <p class="code">&emsp;}</p>
                <p class="code">}</p>
            </div>
            <h3>Output</h3>
            <div class="syntax">

                <p class="output">Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
                    at Main.main(Main.java:4)</p>
            </div>
            <h3>Using try catch</h3>
            <div class="syntax">

                <p class="code">public class Main {</p>
                <p class="code">try {</p>
                <p class="code">&emsp;public static void main(String[ ] args) {</p>
                <p class="code">&emsp;&emsp;int[] myNumbers = {1, 2, 3};</p>
                <p class="code">&emsp;&emsp;System.out.println(myNumbers[10]); // error!
                </p>
                <p class="code">&emsp;} catch(Exception e) {</p>
                <p class="code">&emsp;&emsp;System.out.println("Something went
                    wrong.");</p>
                <p class="code">&emsp;&emsp;}</p>
                <p class="code">&emsp;}</p>
                <p class="code">}</p>
            </div>
            <h3>Output</h3>
            <div class="syntax">

                <p class="output">Something went wrong.</p>
            </div>
        </div>
        <div class="bottom-container">
            <p class="copyright">Â© Group 14.</p>
        </div>

</body>

</html>